### PR TITLE
chore: update protobuf files and wasm client

### PR DESCRIPTION
**Pull request by pablojhl**

### CODE REVIEW

**Review by tim-hm — CHANGES_REQUESTED** [review]
Hi @pablojhl, a few bits from me:

- When bumping the wasm artefact I've been isolating that change to a single commit like [here](https://github.com/NillionNetwork/client-ts/commit/a426d7ea0d8b430b56b8b6b57d250bb9b19a6e76) and including build details in commit-sha.txt. This really just a workaround until the nilvm repo is open source but its helpful if/when we need to bisect problems.
- I've re-run the pipeline and ran it locally, but with this commit tests are now failing.

Lemme know if you need assistance with any of that!

**Comment by pablojhl** [comment]
> * When bumping the wasm artefact I've been isolating that change to a single commit like [here](https://github.com/NillionNetwork/client-ts/commit/a426d7ea0d8b430b56b8b6b57d250bb9b19a6e76) and including build details in commit-sha.txt. This really just a workaround until the nilvm repo is open source but its helpful if/when we need to bisect problems.
> * I've re-run the pipeline and ran it locally, but with this commit tests are now failing.

My fault, I should create it as a draft until the needed changes are merged into the nilvm repo. I tested the commit locally running the nillion-devnet from the branch that contains the changes are pending to merge and the tests are working fine. Anyway, I update the PR to draft until they are merged.

Sorry for the inconvenience.

**Review by tim-hm — APPROVED** [review]
Hi ya, looks good! Some suggestions from me:

- Its not immediately clear that `chore: remove particles` is also a wasm package bump ... might be worth making that distinction but not a show stopper by any stretch
- Given the updated protobuf files (and assuming you're looking to release and updated npm package?), I would also bump the client-vm PATCH

**Comment by pablojhl** [comment]
> Hi ya, looks good! Some suggestions from me:
> 
> * Its not immediately clear that `chore: remove particles` is also a wasm package bump ... might be worth making that distinction but not a show stopper by any stretch
> * Given the updated protobuf files (and assuming you're looking to release and updated npm package?), I would also bump the client-vm PATCH

Regarding the first point, do you mean adding a comment in the PR?

**Pull request merged**
